In [1]:
import torch
import numpy as np

#### 1.张量

In [2]:
x = torch.rand(2,3) #生成满足均匀分布的，大小为两行三列的二维矩阵

In [3]:
x

tensor([[0.7421, 0.8045, 0.9570],
        [0.6342, 0.6501, 0.4155]])

In [4]:
x = torch.randn(2,3) #生成满足标准正态分布分布的，大小为两行三列的二维矩阵

In [5]:
x

tensor([[ 2.1916,  0.9427, -1.7660],
        [-0.0634,  1.1416,  1.6810]])

In [6]:
x = torch.zeros(2,3) #生成全零的，大小为两行三列的二维矩阵

In [7]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
x = torch.ones(2,3,4) #生成全1的，大小为两个三行四列的二维矩阵

In [9]:
x

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [10]:
x.size() #得到数组的shape大小

torch.Size([2, 3, 4])

In [11]:
x.shape #得到数组的形状

torch.Size([2, 3, 4])

In [12]:
x.size(0) #返回x数组第0个维度的大小

2

In [13]:
x.size(2) #返回x数组最后一个维度的大小

4

#### 2.数据类型

In [14]:
x = torch.tensor([6,2],dtype=torch.float32) #使用列表初始化张量,规定数据类型为float32

In [15]:
x

tensor([6., 2.])

In [16]:
x.type() #得到张量中元素的数据类型

'torch.FloatTensor'

In [17]:
#数据类型的转换 torch.float32->torch.float64
x.type(torch.float64)

tensor([6., 2.], dtype=torch.float64)

#### 3.tensor与ndarray类型的转换

In [18]:
a  = np.random.randn(2,3)

In [19]:
x1 = torch.from_numpy(a) #从numpy创建tensor
x1

tensor([[ 1.8994,  0.0933, -1.7788],
        [-0.7827,  0.3408, -0.0942]], dtype=torch.float64)

In [20]:
x1.numpy() #从tensor转换到numpy()

array([[ 1.89939722,  0.09333961, -1.77879596],
       [-0.78270112,  0.34080327, -0.09423767]])

#### 4.张量的运算

In [21]:
x1 = torch.rand(2,3)

In [22]:
x1

tensor([[0.1684, 0.1105, 0.3577],
        [0.2652, 0.1392, 0.1823]])

In [23]:
x2 = torch.rand(2,3)

In [24]:
x1

tensor([[0.1684, 0.1105, 0.3577],
        [0.2652, 0.1392, 0.1823]])

In [25]:
# 加法
x1 + x2

tensor([[1.0374, 0.9266, 1.3315],
        [0.9718, 0.7234, 0.6821]])

In [26]:
# 加法
x1.add(x2) #不进行就地加法

tensor([[1.0374, 0.9266, 1.3315],
        [0.9718, 0.7234, 0.6821]])

In [27]:
# 加法
x1.add_(x2) #进行就地加法

tensor([[1.0374, 0.9266, 1.3315],
        [0.9718, 0.7234, 0.6821]])

In [28]:
x1 #经过就地加法之后x1本身的值会被修改

tensor([[1.0374, 0.9266, 1.3315],
        [0.9718, 0.7234, 0.6821]])

In [29]:
# 广播
x1 + 3

tensor([[4.0374, 3.9266, 4.3315],
        [3.9718, 3.7234, 3.6821]])

In [30]:
# 张量的变形
print(x1.shape)
x1.view(3,2)

torch.Size([2, 3])


tensor([[1.0374, 0.9266],
        [1.3315, 0.9718],
        [0.7234, 0.6821]])

In [31]:
# 张量的展平
x1.view(-1,1) #其中 -1表示根据数量自动计算，1表示列数为1  shape  (n,1)

tensor([[1.0374],
        [0.9266],
        [1.3315],
        [0.9718],
        [0.7234],
        [0.6821]])

In [32]:
# 计算均值
x1.mean()

tensor(0.9455)

In [33]:
# 求和
x1.sum()

tensor(5.6728)

In [34]:
# 返回元素只有一个的变量的张量的标量值
x1.sum().item() # 仅仅适用于张两种元素个数为1的情形

5.672792434692383