#### 张量的自动微分

###### 将Torch.Tensor属性 .requires_grad设置为True
###### pytorch将自动开始跟踪对此张量的所有操作
###### 完成计算以后，可以调用.backward() 并自动计算所有的梯度
###### 该张量的梯度将累加到.grad属性之中

In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
x = torch.ones(2,2,requires_grad=True)

In [3]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
x.requires_grad

True

In [5]:
x.data

tensor([[1., 1.],
        [1., 1.]])

In [6]:
x.grad_fn  #返回值为空

In [7]:
x.grad  #返回值为空

In [8]:
y   = x+2

In [9]:
y #由于y的值是根据x求解出来的所以y的grad_fn不为空

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [10]:
y.grad_fn

In [11]:
z   = y * y + 3

In [12]:
out = z.mean()

In [13]:
out

tensor(12., grad_fn=<MeanBackward0>)

In [14]:
z

tensor([[12., 12.],
        [12., 12.]], grad_fn=<AddBackward0>)

#### 使用自动微分计算梯度

In [15]:
out.backward()  # 微分的结构 dout/dx  out=f(x)  

In [16]:
x.grad  #求解出x的梯度

tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])

In [17]:
x.data   # x本身的值不会因为求解梯度制后发生变化

tensor([[1., 1.],
        [1., 1.]])

In [18]:
# 当不需要进行自动微分计算时 可用 with语句进行包裹
with torch.no_grad():
    print((x**2).requires_grad) #返回值为false表示此时梯度运算不会跟踪这里的x

False


In [19]:
print((x**2).requires_grad) #在不加任何其他语句的限制条件下，x脱离with语句以后会被自动求导机制重新跟踪

True


In [20]:
y   = x.detach() #y拷贝x，y脱离自动求导机制

In [21]:
x.requires_grad

True

In [22]:
y.requires_grad

False

##### 改变require_grad的属性

In [23]:
a   = torch.tensor([2,3],dtype=torch.float32)

In [24]:
a.requires_grad

False

In [25]:
a.requires_grad_(True) #就地改变a的requires_grad属性

tensor([2., 3.], requires_grad=True)